-- 한줄 주석

/*
 * 범위 주석
 * */

ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE;

CREATE USER blu IDENTIFIED BY "Nj09121007!";

GRANT RESOURCE, CONNECT TO blu;

ALTER USER blu DEFAULT TABLESPACE SYSTEM QUOTA UNLIMITED ON SYSTEM;

