-- 한줄 주석

/*
 * 범위 주석
 * */

ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE;

CREATE USER kimyoji IDENTIFIED BY "oracle";

GRANT RESOURCE, CONNECT TO kimyoji;

ALTER USER kimyoji DEFAULT TABLESPACE SYSTEM QUOTA UNLIMITED ON SYSTEM;

